import type { Metadata } from "next";
import { Architects_Daughter, Barlow, Cedarville_Cursive, Inter, Lily_Script_One, Lora, PT_Sans, PT_Sans_Caption, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_layout_components/Header";
import Footer from "./_layout_components/Footer";
import BackToTop from "@/components/BackToTop";

const inter = Inter({ subsets: ["latin"],variable:"--font-inter" });
const lora = Lora({ subsets: ["latin"],variable:"--font-lora" });
const barlow = Barlow({ weight:"500",subsets: ["latin"],variable:"--font-barlow" });
const poppins = Poppins({ weight:"500",subsets: ["latin"],variable:"--font-poppins" });
const architects =Architects_Daughter({ weight:"400",subsets:["latin"],variable:"--font-architects"})
const cursive =Cedarville_Cursive({ weight:"400",subsets:["latin"],variable:"--font-cursive"})
const lily =Lily_Script_One({ weight:"400",subsets:["latin"],variable:"--font-lily"})
const pt =PT_Sans_Caption({ weight:"400",subsets:["latin"],variable:"--font-pt"})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poppins.variable} ${lora.variable} ${architects.variable} ${cursive.variable} ${lily.variable} ${pt.variable}`}>
        <Header />
        {children}
        <BackToTop/>
        <Footer />
      </body>
    </html>
  );
}
